Repository TeamKeepin/Keepin-iOS, pull requests merged in 2021-08, with the labels that each got.

#258 [feat] #257 화면 회전 막기
  Keepin_iOS/Keepin_iOS/Info.plist
Labels: 3wns, feat, pull request

#259 [fix] 마이페이지 친구상세 label 수정
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/MyPageDetailVC.xib
Labels: fix, silver, pull request

#260 [fix] 친구이름수정 화면전환
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/MyPageFriendFixVC.swift
Labels: fix, silver

#261 [FIX] 프로필 편집 화면전환 수정
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/EditProfile/MyPageEditNameVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/EditProfile/MyPageEditPhoneVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/EditProfile/MyPageEditPwVC.swift
Labels: fix, silver, pull request

#281 [feat] #272 새친구 등록하기 alert창 추가
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusFriend/KeepinPlusFriendVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/MyPageDetailVC.swift
Labels: feat, silver

#282 [feat] #276 프로필 편집 이메일, 생일 변경 불가 추가
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/MyPageProfileVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/MyPageProfileVC.xib
Labels: feat, silver

#283 [fix] #240 새친구등록하기 글자 수 제한
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/EditProfile/MyPageEditNameVC.swift
Labels: fix, silver

#285 [#284] 친구등록하기 글자수 제한
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusFriend/KeepinPlusFriendVC.swift
Labels: feat, silver

#288 [#287] 홈화면 리마인더 이동 삭제
  Keepin_iOS/Keepin_iOS/Sources/Home/Cell/HomeEventTVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Home/Cell/HomeEventTVC.xib
  Keepin_iOS/Keepin_iOS/Sources/Home/HomeVC.swift
Labels: seawater🌊, pull request

#289 [#256] 다크모드 막기
  Keepin_iOS/Keepin_iOS/Info.plist
Labels: 3wns, feat

#292 [#291] 회원가입 이메일 중복체크
  Keepin_iOS/Keepin_iOS/Sources/Join/DataManager/JoinDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/Join/DataModel/JoinRequest.swift
  Keepin_iOS/Keepin_iOS/Sources/Join/JoinFirstVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Join/JoinSecondVC.swift
Labels: seawater🌊, pull request

#293 [#103] 회원가입 서버연결 완료
  Keepin_iOS/Keepin_iOS/Sources/Join/DataManager/JoinDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/Join/JoinFirstVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Join/JoinSecondVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Join/JoinSecondVC.xib
Labels: seawater🌊, pull request

#294 [#275] 비밀번호 변경 : 비밀번호가 규칙에 안 맞을 경우
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/EditProfile/MyPageEditPwVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/EditProfile/MyPageEditPwVC.xib
Labels: feat, silver, pull request

#295 [#273] 비밀번호 변경: 비밀번호가 일치하지 않는 경우
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/EditProfile/MyPageEditPwVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/EditProfile/MyPageEditPwVC.xib
Labels: silver, pull request

#297 [#296] 키핀하기 뷰 UI 다시 구성
  Keepin_iOS/Keepin_iOS.xcodeproj/project.pbxproj
  Keepin_iOS/Keepin_iOS/Configuration/Base/BaseTBC.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusMain/KeepinPlusMainVC.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusMain/KeepinPlusMainVC.xib
Labels: seawater🌊, pull request

#303 [#302] 키핀하기 카테고리 최대 2개 선택 추가
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusMain/KeepinPlusMainVC.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusMain/KeepinPlusMainVC.xib
Labels: seawater🌊, pull request

#304 [feat] #266 메모하기 아이콘 적용하기
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icnCheckBox.imageset/Contents.json
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icnCheckBox.imageset/icnCheckBox.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icnCheckBox.imageset/icnCheckBox@2x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icnCheckBox.imageset/icnCheckBox@3x.png
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/MyPageDetailVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/MyPageDetailVC.xib
Labels: feat, silver, pull request

#306 [#305] 키핀하기 맨 아래 placeholder 설정
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusMain/KeepinPlusMainVC.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusMain/KeepinPlusMainVC.xib
Labels: seawater🌊, pull request

#307 [#298] 키핀하기 마지막 줄 수에 맞춰서 textview 늘어나도록
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusMain/KeepinPlusMainVC.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusMain/KeepinPlusMainVC.xib
Labels: seawater🌊, pull request
