Repository TeamKeepin/Keepin-iOS, pull requests merged in 2021-09, with the labels that each got.

#309 [#308] 키핀하기 - 키보드이슈해결
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusMain/KeepinPlusMainVC.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusMain/KeepinPlusMainVC.xib
Labels: seawater🌊, pull request

#311 [#310] 키핀하기 뷰 DatePicker 추가
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusMain/KeepinPlusMainVC.swift
Labels: seawater🌊, pull request

#314 [#313] 친구선택 뷰 UI 다시 구성
  Keepin_iOS/Keepin_iOS.xcodeproj/project.pbxproj
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusMain/KeepinPlusMainVC.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusMain/KeepinPlusMainVC.xib
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/SelectFriend/Cell/SelectFriendMessageTVC.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/SelectFriend/Cell/SelectFriendMessageTVC.xib
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/SelectFriend/Cell/SelectFriendTitleTVC.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/SelectFriend/SelectFriendVC.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/SelectFriend/SelectFriendVC.xib
Labels: seawater🌊, pull request

#318 [#218] 키핀하기 서버통신
  Keepin_iOS/Keepin_iOS.xcodeproj/project.pbxproj
  Keepin_iOS/Keepin_iOS/Sources/EmailLogin/EmailLoginVC.xib
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusMain/DataManager/KeepinPlusMainDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusMain/KeepinPlusMainVC.swift
Labels: seawater🌊, pull request

#320 [#319] 친구선택뷰 -> 키핀하기 데이터 전달
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusMain/KeepinPlusMainVC.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/SelectFriend/SelectFriendVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/DataManager/MyPageHomeDataManager.swift
Labels: seawater🌊, pull request

#322 [#321] friendIdx 2명이상일때 안보내지던거 해결
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusMain/DataManager/KeepinPlusMainDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusMain/KeepinPlusMainVC.swift
Labels: seawater🌊, pull request

#323 [#317] 받은/준, 카테고리 전달
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusMain/KeepinPlusMainVC.swift
Labels: seawater🌊, pull request

#325 [#324] 키핀하기 이미지 전송 여러장
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusMain/DataManager/KeepinPlusMainDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusMain/KeepinPlusMainVC.swift
Labels: seawater🌊, pull request

#327 [#326] 키핀하기 로티뷰 추가
  Keepin_iOS/Keepin_iOS.xcodeproj/project.pbxproj
  Keepin_iOS/Keepin_iOS/Configuration/Lottie/keepin.json
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusMain/KeepinPlusMainVC.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusMain/KeepinPlusMainVC.xib
Labels: seawater🌊, pull request

#332 Feat/#331 hs
  Keepin_iOS/Keepin_iOS/Assets.xcassets/listReminderImportant.imageset/Contents.json
  Keepin_iOS/Keepin_iOS/Assets.xcassets/listReminderNotimportant.imageset/Contents.json
  Keepin_iOS/Keepin_iOS/Sources/Home/Cell/HomeEventTVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Home/Cell/HomeEventTVC.xib
  Keepin_iOS/Keepin_iOS/Sources/Home/Cell/HomeTopTVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Home/Cell/HomeTopTVC.xib
  Keepin_iOS/Keepin_iOS/Sources/Home/HomeVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Home/HomeVC.xib
Labels: seawater🌊, pull request

#334 [#333] 메모하기 연필 아이콘 추가하기
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icnEdit.imageset/Contents.json
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icnEdit.imageset/icnEdit.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icnEdit.imageset/icnEdit@2x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icnEdit.imageset/icnEdit@3x.png
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/MyPageDetailVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/MyPageDetailVC.xib
Labels: feat, silver

#336 [#335] 메모하기 아이콘 클릭하면 수정 가능, 불가능 완료
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/MyPageDetailVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/MyPageDetailVC.xib
Labels: feat, silver

#344 Feat/#262
  Keepin_iOS/Keepin_iOS.xcodeproj/project.pbxproj
  Keepin_iOS/Keepin_iOS/Configuration/Extension/Date.swift
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderHome/Cell/ReminderCVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderHome/Cell/ReminderSwapCVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderHome/Cell/ReminderSwapCVC.xib
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderHome/Cell/ReminderTVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderHome/Cell/ReminderTVC.xib
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderHome/DataManager/ReminderHomeDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderHome/DataModel/ReminderHomeRequest.swift
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderHome/DataModel/ReminderHomeResponse.swift
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderHome/ReminderVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderHome/ReminderVC.xib
Labels: 3wns, pull request

#346 [#345] 친구명수에 따라 분기처리
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentDetail/PresentDetailVC.swift
Labels: 3wns, pull request

#347 [feat] 서비스 이용약관 페이지 연결
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/MyPageProfileVC.swift
Labels: feat, silver

#349 [feat] 개인정보 처리방침 페이지 연결
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/MyPageProfileVC.swift
Labels: feat, silver

#351 [#350] 키핀하기 - 새친구등록 연결
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusMain/DataManager/KeepinPlusMainDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusMain/KeepinPlusMainVC.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/SelectFriend/SelectFriendVC.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/SelectFriend/SelectFriendVC.xib
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentMoaHome/PresentMoaVC.swift
Labels: seawater🌊, pull request

#353 [feat] 이메일 작성 페이지 연결
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/MyPageProfileVC.swift
Labels: feat, silver

#354 Feat/#341
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderAdd/DataManager/ReminderDetailDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderAdd/ReminderAddVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderHome/Cell/ReminderSwapCVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderHome/ReminderVC.swift
Labels: 3wns, pull request

#356 Feat/#330 hs
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusMain/KeepinPlusMainVC.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusMain/KeepinPlusMainVC.xib
Labels: pull request

#357 [#340] 홈화면 하단 reminder empty 뷰 추가
  Keepin_iOS/Keepin_iOS/Assets.xcassets/imgEmptySpeechSmall.imageset/Contents.json
  Keepin_iOS/Keepin_iOS/Assets.xcassets/imgEmptySpeechSmall.imageset/imgEmptySpeechSmall.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/imgEmptySpeechSmall.imageset/imgEmptySpeechSmall@2x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/imgEmptySpeechSmall.imageset/imgEmptySpeechSmall@3x.png
  Keepin_iOS/Keepin_iOS/Sources/Home/Cell/HomeEventTVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Home/Cell/HomeEventTVC.xib
  Keepin_iOS/Keepin_iOS/Sources/Home/Cell/HomeTopSingleTVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Home/Cell/HomeTopSingleTVC.xib
  Keepin_iOS/Keepin_iOS/Sources/Home/HomeVC.swift
Labels: seawater🌊, pull request

#359 [#358] 홈 상단 empty view 추가
  Keepin_iOS/Keepin_iOS/Sources/Home/Cell/HomeTopTVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Home/Cell/HomeTopTVC.xib
  Keepin_iOS/Keepin_iOS/Sources/Home/DataManager/HomeDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/Home/DataModel/HomeResponse.swift
  Keepin_iOS/Keepin_iOS/Sources/Home/HomeVC.swift
Labels: seawater🌊, pull request

#360 [#86] 홈화면 랜덤 웰컴메시지 적용
  Keepin_iOS/Keepin_iOS/Sources/Home/Cell/HomeTopTVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Home/DataManager/HomeDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/Home/HomeVC.swift
Labels: seawater🌊, pull request

#361 [#76] 키핀하기뷰 다시 열때 데이터 초기화
  Keepin_iOS/Keepin_iOS/Configuration/Base/BaseTBC.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusMain/KeepinPlusMainVC.swift
Labels: seawater🌊, pull request

#362 Feat/#355 3wns
  Keepin_iOS/Keepin_iOS/Assets.xcassets/imgEmptyEyes.imageset/Contents.json
  Keepin_iOS/Keepin_iOS/Assets.xcassets/imgEmptyEyes.imageset/imgEmptyEyes.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/imgEmptyEyes.imageset/imgEmptyEyes@2x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/imgEmptyEyes.imageset/imgEmptyEyes@3x.png
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderHome/Cell/ReminderSwapCVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderHome/Cell/ReminderSwapCVC.xib
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderHome/ReminderVC.swift
Labels: 3wns, pull request

#364 [#363] 검색 empty뷰 추가
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/Search/SearchVC.swift
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/Search/SearchVC.xib
Labels: 3wns, feat

#366 Feat/#365 3wns
  Keepin_iOS/Keepin_iOS/Assets.xcassets/imgEmpty.imageset/Contents.json
  Keepin_iOS/Keepin_iOS/Assets.xcassets/imgEmpty.imageset/imgEmpty.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/imgEmpty.imageset/imgEmpty@2x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/imgEmpty.imageset/imgEmpty@3x.png
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentMoaHome/PresentMoaVC.swift
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentMoaHome/PresentMoaVC.xib
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/Search/SearchVC.swift
Labels: 3wns, pull request

#369 [#368] 친구검색뷰 - 전체 친구목록 보이도록
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/SelectFriend/Cell/SelectFriendMessageTVC.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/SelectFriend/SelectFriendVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/DataManager/MyPageHomeDataManager.swift
Labels: seawater🌊, pull request

#371 [#370] 전체 친구목록에 추가되지 않는 문제 해결
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/SelectFriend/SelectFriendVC.swift
Labels: seawater🌊, pull request

#373 [#372] 홈 데이터 새로고침 시점 고침
  Keepin_iOS/Keepin_iOS/Sources/Home/HomeVC.swift
Labels: seawater🌊, pull request

#375 [#374] 키핀하기 이후 모아보기 새로고침
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentMoaHome/PresentMoaVC.swift
Labels: seawater🌊, pull request

#377 [#376] 키핀하기뷰 메모 입력 안했을때 안내문구 그대로 넘어가는 이슈 해결
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusMain/KeepinPlusMainVC.swift
Labels: seawater🌊, pull request

#378 Feat/#343 3wns
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderHome/Cell/ReminderSwapCVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderHome/Cell/ReminderSwapCVC.xib
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderHome/Cell/ReminderTVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderHome/ReminderVC.swift
Labels: 3wns, pull request

#379 [feat] 계정삭제 서버통신
  Keepin_iOS/Keepin_iOS.xcodeproj/project.pbxproj
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/DataManager/MyPageProfileDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/DataModel/MyPageDeleteIdResponse.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/MyPageProfileVC.swift
Labels: feat, silver, server

#383 [#380] 친구이름 오토레이아웃 수정
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/Cell/MyPageHomeFriendCVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/Cell/MyPageHomeTopCVC.xib
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/MyPageHomeVC.swift
Labels: fix, silver

#388 [#387] 자동로그인/로그아웃 구현
  Keepin_iOS/Keepin_iOS/Configuration/Constants.swift
  Keepin_iOS/Keepin_iOS/SceneDelegate.swift
  Keepin_iOS/Keepin_iOS/Sources/EmailLogin/DataManager/EmailLoginDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/EmailLogin/EmailLoginVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Home/Cell/HomeTopTVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Home/DataManager/HomeDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/Home/HomeVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/MyPageProfileVC.swift
Labels: seawater🌊, pull request

#390 [#389] 로그아웃후 재로그인시 이슈 해결
  Keepin_iOS/Keepin_iOS/Configuration/Base/BaseTBC.swift
  Keepin_iOS/Keepin_iOS/Sources/EmailLogin/DataManager/EmailLoginDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/EmailLogin/EmailLoginVC.swift
  Keepin_iOS/Keepin_iOS/Sources/EmailLogin/EmailLoginVC.xib
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/Cell/MyPageHomeFriendCVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/MyPageHomeVC.swift
Labels: seawater🌊, pull request

#392 [#391] 키핀 안올라오는 문제 해결
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusMain/DataManager/KeepinPlusMainDataManager.swift
Labels: seawater🌊, pull request

#394 [#267] 메모하기 서버통신 완료, 마이페이지 홈 상단부분 수정
  Keepin_iOS/Keepin_iOS.xcodeproj/project.pbxproj
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/DataManager/MyPageDetailDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/DataModel/MyPageDetailRequest.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/DataModel/MyPageMemoResponse.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/MyPageDetailVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/MyPageDetailVC.xib
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/Cell/MyPageHomeTopCVC.xib
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/MyPageHomeVC.xib
Labels: feat, silver, server

#396 [#395] 마이페이지 상단 부분 오토레이아웃 수정
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/MyPageDetailVC.xib
Labels: fix, silver

#399 [#398] textfield 오토커렉션 해제
  Keepin_iOS/Keepin_iOS/Sources/Join/JoinFirstVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Join/JoinFirstVC.xib
  Keepin_iOS/Keepin_iOS/Sources/Join/JoinSecondVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Join/JoinSecondVC.xib
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusMain/KeepinPlusMainVC.xib
Labels: seawater🌊, pull request

#400 [#397] 비밀번호 찾기 UI
  Keepin_iOS/Keepin_iOS.xcodeproj/project.pbxproj
  Keepin_iOS/Keepin_iOS/Assets.xcassets/findPw.imageset/Contents.json
  Keepin_iOS/Keepin_iOS/Assets.xcassets/findPw.imageset/findPw.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/findPw.imageset/findPw@2x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/findPw.imageset/findPw@3x.png
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/EditProfile/MyPageEditPwVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/EditProfile/MyPageEditPwVC.xib
  Keepin_iOS/Keepin_iOS/Sources/PwFindVC.swift
  Keepin_iOS/Keepin_iOS/Sources/PwFindVC.xib
Labels: feat, silver

#405 [#404] 팀키핀 영우선배 이름 변경
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/EditProfile/TeamKeepinVC.xib
Labels: fix, silver

#406 [#402] textfield 오토컬렉션 해제
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/MyPageDetailVC.xib
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/MyPageFriendFixVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/MyPageFriendFixVC.xib
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/MyPageHomeVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/EditProfile/MyPageEditNameVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/EditProfile/MyPageEditNameVC.xib
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/EditProfile/MyPageEditPhoneVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/EditProfile/MyPageEditPhoneVC.xib
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/EditProfile/MyPageEditPwVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/EditProfile/MyPageEditPwVC.xib
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/EditProfile/TeamKeepinVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/MyPageProfileVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/MyPageProfileVC.xib
Labels: feat, silver

#407 [#299] 마이페이지 선물 클락하면 상세보기로 가기
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/Cell/MyPagePresentMoaCVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/Cell/MyPagePresentMoaCVC.xib
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/DataModel/MyPagePresentMoaResponse.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/MyPageDetailVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/MyPageDetailVC.xib
Labels: feat, silver

#408 [#270] 새친구 등록 중복된 친구이름 제한
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusFriend/KeepinPlusFriendVC.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusFriend/KeepinPlusFriendVC.xib
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/MyPageDetailVC.xib
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/DataManager/PlusFriendDataManager.swift
Labels: feat, silver, server

#409 [#268] 마이페이지 상세 empty뷰 적용하기
  Keepin_iOS/Keepin_iOS/Assets.xcassets/AppIcon.appiconset/Contents.json
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/MyPageDetailVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/MyPageDetailVC.xib
Labels: feat, silver
