Repository TeamKeepin/Keepin-iOS, pull requests merged in 2021-07, with the labels that each got.

#4 #1 완료
  Keepin_iOS/Keepin_iOS.xcodeproj/project.pbxproj
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icBack.imageset/Contents.json
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icBack.imageset/icBack.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icBack.imageset/icBack@2x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icBack.imageset/icBack@3x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/imgHomeRandom.imageset/Contents.json
  Keepin_iOS/Keepin_iOS/Assets.xcassets/imgHomeRandom.imageset/imgHomeRandom.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/imgHomeRandom.imageset/imgHomeRandom@2x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/imgHomeRandom.imageset/imgHomeRandom@3x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/imgReminderDivideLine.imageset/Contents.json
  Keepin_iOS/Keepin_iOS/Assets.xcassets/imgReminderDivideLine.imageset/imgReminderDivideLine.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/imgReminderDivideLine.imageset/imgReminderDivideLine@2x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/imgReminderDivideLine.imageset/imgReminderDivideLine@3x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/imgReminderImpor.imageset/Contents.json
  Keepin_iOS/Keepin_iOS/Assets.xcassets/imgReminderImpor.imageset/imgReminderImpor.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/imgReminderImpor.imageset/imgReminderImpor@2x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/imgReminderImpor.imageset/imgReminderImpor@3x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/imgReminderNotImpor.imageset/Contents.json
  Keepin_iOS/Keepin_iOS/Assets.xcassets/imgReminderNotImpor.imageset/imgReminderNotImpor.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/imgReminderNotImpor.imageset/imgReminderNotImpor@2x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/imgReminderNotImpor.imageset/imgReminderNotImpor@3x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/listReminderHome.imageset/Contents.json
  Keepin_iOS/Keepin_iOS/Assets.xcassets/listReminderHome.imageset/listReminderHome.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/listReminderHome.imageset/listReminderHome@2x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/listReminderHome.imageset/listReminderHome@3x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/listReminderHomeImp.imageset/Contents.json
  Keepin_iOS/Keepin_iOS/Assets.xcassets/listReminderHomeImp.imageset/listReminderHomeImp.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/listReminderHomeImp.imageset/listReminderHomeImp@2x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/listReminderHomeImp.imageset/listReminderHomeImp@3x.png
  Keepin_iOS/Keepin_iOS/Sources/Home/Cell/HomeEventTVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Home/Cell/HomeEventTVC.xib
  Keepin_iOS/Keepin_iOS/Sources/Home/Cell/HomeTopTVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Home/Cell/HomeTopTVC.xib
  Keepin_iOS/Keepin_iOS/Sources/Home/HomeVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Home/HomeVC.xib
Labels: pull request, seawater🌊

#9 Dev yijoon
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icArchive.imageset/Contents.json
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icArchive.imageset/icArchive.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icArchive.imageset/icArchive@2x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icArchive.imageset/icArchive@3x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icReminder.imageset/Contents.json
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icReminder.imageset/icReminder.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icReminder.imageset/icReminder@2x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icReminder.imageset/icReminder@3x.png
  Keepin_iOS/Keepin_iOS/Configuration/Extension/UIButton.swift
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentMoaHome/Cell/PresentMoaCVC.xib
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentMoaHome/PresentMoaVC.swift
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentMoaHome/PresentMoaVC.xib
Labels: 3wns, pull request

#12 홈 뷰 수정사항 수정함
  Keepin_iOS/Keepin_iOS/Sources/Home/Cell/HomeTopTVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Home/Cell/HomeTopTVC.xib
  Keepin_iOS/Keepin_iOS/Sources/Home/HomeVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Home/HomeVC.xib
Labels: pull request, seawater🌊

#17 로그인 뷰 끝!
  Keepin_iOS/Keepin_iOS/Sources/EmailLogin/EmailLoginVC.swift
  Keepin_iOS/Keepin_iOS/Sources/EmailLogin/EmailLoginVC.xib
Labels: pull request, seawater🌊

#20 [feat] #11 프로그래스바 기능, 카테고리 버튼
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icCateAnniversary.imageset/Contents.json
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icCateAnniversary.imageset/icCateAnniversary.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icCateAnniversary.imageset/icCateAnniversary@2x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icCateAnniversary.imageset/icCateAnniversary@3x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icCateBirthday.imageset/Contents.json
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icCateBirthday.imageset/icCateBirthday.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icCateBirthday.imageset/icCateBirthday@2x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icCateBirthday.imageset/icCateBirthday@3x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icCateCelebrate.imageset/Contents.json
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icCateCelebrate.imageset/icCateCelebrate.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icCateCelebrate.imageset/icCateCelebrate@2x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icCateCelebrate.imageset/icCateCelebrate@3x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icCateCheer.imageset/Contents.json
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icCateCheer.imageset/icCateCheer.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icCateCheer.imageset/icCateCheer@2x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icCateCheer.imageset/icCateCheer@3x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icCateCompliment.imageset/Contents.json
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icCateCompliment.imageset/icCateCompliment.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icCateCompliment.imageset/icCateCompliment@2x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icCateCompliment.imageset/icCateCompliment@3x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icCateEtc.imageset/Contents.json
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icCateEtc.imageset/icCateEtc.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icCateEtc.imageset/icCateEtc@2x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icCateEtc.imageset/icCateEtc@3x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icCateSurprise.imageset/Contents.json
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icCateSurprise.imageset/icCateSurprise.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icCateSurprise.imageset/icCateSurprise@2x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icCateSurprise.imageset/icCateSurprise@3x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icCateThanks.imageset/Contents.json
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icCateThanks.imageset/icCateThanks.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icCateThanks.imageset/icCateThanks@2x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icCateThanks.imageset/icCateThanks@3x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/imgPhotoDetailLine.imageset/Contents.json
  Keepin_iOS/Keepin_iOS/Assets.xcassets/imgPhotoDetailLine.imageset/imgPhotoDetailLine.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/imgPhotoDetailLine.imageset/imgPhotoDetailLine@2x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/imgPhotoDetailLine.imageset/imgPhotoDetailLine@3x.png
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentDetail/PresentDetailVC.swift
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentDetail/PresentDetailVC.xib
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/Search/SearchVC.xib
Labels: 3wns, pull request

#22 [fix] #10 전체 스크롤 다이나믹 높이
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentMoaHome/Cell/PresentMoaCVC.xib
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentMoaHome/PresentMoaVC.swift
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentMoaHome/PresentMoaVC.xib
Labels: 3wns, fix

#23 회원가입 첫 뷰 완료!
  Keepin_iOS/Keepin_iOS/Sources/Join/JoinFirstVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Join/JoinFirstVC.xib
Labels: feat, pull request

#28 [fix] #27 커스텀탭바 버그 수정
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentMoaHome/PresentMoaVC.swift
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentMoaHome/PresentMoaVC.xib
Labels: 3wns, pull request

#30 [feat] 회원가입 두번째 뷰
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icSelect.imageset/Contents.json
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icSelect.imageset/icSelect.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icSelect.imageset/icSelect@2x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icSelect.imageset/icSelect@3x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icSelectActive.imageset/Contents.json
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icSelectActive.imageset/icSelectActive.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icSelectActive.imageset/icSelectActive@2x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icSelectActive.imageset/icSelectActive@3x.png
  Keepin_iOS/Keepin_iOS/Sources/Join/JoinSecondVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Join/JoinSecondVC.xib
Labels: pull request, seawater🌊

#32 Dev yijoon
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/Search/AfterCate/AfterCatVC.swift
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/Search/AfterCate/AfterCatVC.xib
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/Search/SearchVC.swift
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/Search/SearchVC.xib
Labels: 3wns, feat

#39 Dev yijoon
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icAlarm.imageset/Contents.json
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icAlarm.imageset/icAlarm.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icAlarm.imageset/icAlarm@2x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icAlarm.imageset/icAlarm@3x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icCalander.imageset/Contents.json
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icCalander.imageset/icCalander.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icCalander.imageset/icCalander@2x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icCalander.imageset/icCalander@3x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icImportantActive.imageset/Contents.json
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icImportantActive.imageset/icImportantActive.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icImportantActive.imageset/icImportantActive@2x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icImportantActive.imageset/icImportantActive@3x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icImportantDefault.imageset/Contents.json
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icImportantDefault.imageset/icImportantDefault.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icImportantDefault.imageset/icImportantDefault@2x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icImportantDefault.imageset/icImportantDefault@3x.png
  Keepin_iOS/Keepin_iOS/Configuration/Extension/UIViewController.swift
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderAdd/ReminderAddVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderAdd/ReminderAddVC.xib
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderHome/ReminderVC.swift
Labels: 3wns, pull request

#40 [feat] #26 마이페이지 친구 이름 수정페이지 완료
  Keepin_iOS/Keepin_iOS/Assets.xcassets/trailingIcon.imageset/Contents.json
  Keepin_iOS/Keepin_iOS/Assets.xcassets/trailingIcon.imageset/trailingIcon.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/trailingIcon.imageset/trailingIcon@2x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/trailingIcon.imageset/trailingIcon@3x.png
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/MyPageDetailVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/MyPageFriendFixVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/MyPageFriendFixVC.xib
Labels: feat, silver

#44 [feat] 리마인더 등록하기 완료
  Keepin_iOS/Keepin_iOS/Configuration/Extension/UIViewController.swift
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderAdd/ReminderAddVC.swift
Labels: 3wns, pull request

#46 [fix] #45 picker 높이 수정
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderAdd/ReminderAddVC.swift
Labels: 3wns, pull request

#48 [feat] #47 상세보기 삭제 다이얼로그
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentDetail/PresentDetailVC.swift
Labels: 3wns, pull request

#49 [feat] #43 새친구 등록하기 UI 완료
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusFriend/KeepinPlusFriendVC.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusFriend/KeepinPlusFriendVC.xib
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/MyPageProfileVC.xib
Labels: feat, silver

#52 [feat] #29 프로필 편집 UI 완료
  Keepin_iOS/Keepin_iOS/Assets.xcassets/keyboardArrowRight.imageset/Contents.json
  Keepin_iOS/Keepin_iOS/Assets.xcassets/keyboardArrowRight.imageset/keyboardArrowRight.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/keyboardArrowRight.imageset/keyboardArrowRight@2x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/keyboardArrowRight.imageset/keyboardArrowRight@3x.png
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/MyPageHomeVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/EditProfile/MyPageEditNameVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/EditProfile/MyPageEditNameVC.xib
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/MyPageProfileVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/MyPageProfileVC.xib
Labels: feat, silver

#53 리마인더 테이블 뷰 관련 완료
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderHome/Cell/ReminderTVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderHome/Cell/ReminderTVC.xib
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderHome/ReminderVC.swift
Labels: 3wns, feat

#56 [fix] #54 셀 높이 수정
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderHome/ReminderVC.swift
Labels: 3wns, pull request

#59 [feat] #57 프로필 편집_번호 변경 UI
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/EditProfile/MyPageEditNameVC.xib
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/EditProfile/MyPageEditPhoneVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/EditProfile/MyPageEditPhoneVC.xib
Labels: feat, silver

#60 [feat] 키핀하기 뷰 UI
  Keepin_iOS/Keepin_iOS/Info.plist
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusHome/Cell/KeepinPlusCategoryTVC.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusHome/Cell/KeepinPlusCategoryTVC.xib
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusHome/Cell/KeepinPlusImageTVC.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusHome/Cell/KeepinPlusImageTVC.xib
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusHome/Cell/KeepinPlusInputTVC.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusHome/Cell/KeepinPlusInputTVC.xib
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusHome/Cell/KeepinPlusSearchTVC.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusHome/Cell/KeepinPlusSearchTVC.xib
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusHome/Cell/KeepinPlusWriteTVC.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusHome/Cell/KeepinPlusWriteTVC.xib
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusHome/Cell/KeppinPlusSelectTVC.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusHome/Cell/KeppinPlusSelectTVC.xib
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusHome/KeepinPlusVC.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusHome/KeepinPlusVC.xib
Labels: feat, seawater🌊

#63 [feat] #55 마이페이지 비밀번호 변경 UI완성, 번호,이름 변경 구현 완료
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/EditProfile/MyPageEditNameVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/EditProfile/MyPageEditNameVC.xib
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/EditProfile/MyPageEditPhoneVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/EditProfile/MyPageEditPhoneVC.xib
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/EditProfile/MyPageEditPwVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/EditProfile/MyPageEditPwVC.xib
Labels: feat, silver

#64 [feat] #62 프로필 편집 로그아웃 구현 완료
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/MyPageProfileVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/MyPageProfileVC.xib
Labels: feat, silver

#68 [fix] #41 아이콘 변경
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icNext.imageset/Contents.json
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icNext.imageset/icNext.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icNext.imageset/icNext@2x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icNext.imageset/icNext@3x.png
  Keepin_iOS/Keepin_iOS/Sources/Home/Cell/HomeEventTVC.xib
Labels: fix, pull request, seawater🌊

#69 [feat] 키핀하기 뷰 datepicker 적용
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusHome/KeepinPlusVC.swift
Labels: pull request, seawater🌊

#71 [fix] #42 회원가입생일-> datePicker로 변경
  Keepin_iOS/Keepin_iOS/Sources/Join/JoinSecondVC.swift
Labels: fix, pull request, seawater🌊

#78 [feat] #70 closed
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusHome/KeepinPlusVC.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusHome/KeepinPlusVC.xib
Labels: feat, seawater🌊

#80 [feat] #67 baseURL, 토큰
  Keepin_iOS/Keepin_iOS/Configuration/Constants.swift
  Keepin_iOS/Keepin_iOS/Configuration/Secret/Token.swift
Labels: 3wns, pull request

#81 [fix] #7 마이페이지 헤더뷰 수정완료
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/MyPageHomeVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/MyPageProfileVC.swift
Labels: fix, silver

#82 [feat] #66 키핀하기 새친구등록 수정
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusFriend/KeepinPlusFriendVC.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusFriend/KeepinPlusFriendVC.xib
Labels: fix, silver

#83 [fix] #79 키핀하기 상단 여백 줌 closed
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusHome/Cell/KeepinPlusBlankTVC.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusHome/KeepinPlusVC.swift
Labels: fix, pull request, seawater🌊

#85 [feat] #84 모아보기 받은/준 서버통신
  Keepin_iOS/Keepin_iOS.xcodeproj/project.pbxproj
  Keepin_iOS/Keepin_iOS/Configuration/Secret/Token.swift
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentMoaHome/DataManager/PresentMoaHomeDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentMoaHome/DataModel/PresentMoaHomeRequest.swift
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentMoaHome/DataModel/PresentMoaHomeResponse.swift
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentMoaHome/PresentMoaVC.swift
Labels: 3wns, pull request

#91 #88 검색 검색어 서버통신
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/Search/DataManager/SearchDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/Search/DataModel/SearchResponse.swift
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/Search/SearchVC.swift
Labels: 3wns, feat

#92 [feat] /random 서버연결 완료
  Keepin_iOS/Keepin_iOS/Sources/Home/DataManager/HomeDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/Home/DataModel/HomeResponse.swift
  Keepin_iOS/Keepin_iOS/Sources/Home/HomeVC.swift
Labels: feat, pull request, seawater🌊

#96 [feat] #94 로그인 서버연결 closed
  Keepin_iOS/Keepin_iOS/Sources/EmailLogin/DataManager/EmailLoginDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/EmailLogin/DataModel/EmailLoginRequest.swift
  Keepin_iOS/Keepin_iOS/Sources/EmailLogin/DataModel/EmailLoginResponse.swift
  Keepin_iOS/Keepin_iOS/Sources/EmailLogin/EmailLoginVC.swift
  Keepin_iOS/Keepin_iOS/Sources/EmailLogin/EmailLoginVC.xib
Labels: pull request, seawater🌊, server

#98 [feat] #93 마이페이지 유저별 키핀수 서버통신 완료
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/DataManager/MyPageHomeDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/DataModel/MyPageHomeResponse.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/MyPageHomeVC.swift
Labels: feat, pull request, server, silver

#101 [feat] #97 로그인 실패시 alert, 성공시 홈화면 전환 closed
  Keepin_iOS/Keepin_iOS/Sources/EmailLogin/DataManager/EmailLoginDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/EmailLogin/EmailLoginVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Home/HomeVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Login/LoginFirstVC.swift
Labels: feat, pull request, seawater🌊, server

#102 [feat] #90 검색 카테고리 서버통신
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentMoaHome/PresentMoaVC.swift
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/Search/AfterCate/AfterCatVC.swift
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/Search/DataManager/SearchDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/Search/SearchVC.swift
Labels: 3wns, pull request

#105 [feat] #104 첫화면에서 회원가입 화면 전환 closed
  Keepin_iOS/Keepin_iOS/Sources/Join/JoinFirstVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Join/JoinFirstVC.xib
  Keepin_iOS/Keepin_iOS/Sources/Login/LoginFirstVC.swift
Labels: feat, pull request, seawater🌊

#108 [fix] #106 로그인뷰 상단 레이아웃 다시잡음
  Keepin_iOS/Keepin_iOS/Sources/EmailLogin/EmailLoginVC.xib
Labels: fix, pull request, seawater🌊

#111 [feat] 로그인시 홈화면으로 이름 넘김
  Keepin_iOS/Keepin_iOS/Sources/EmailLogin/DataManager/EmailLoginDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/Home/Cell/HomeTopTVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Join/DataModel/JoinRequest.swift
  Keepin_iOS/Keepin_iOS/Sources/Join/DataModel/JoinResponse.swift
Labels: feat, pull request, seawater🌊

#113 [fix] #99 마이페이지 상단부분 수정 완료
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/Cell/MyPageHomeTopCVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/Cell/MyPageHomeTopCVC.xib
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/DataManager/MyPageHomeDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/MyPageHomeVC.swift
Labels: fix, pull request, server, silver

#114 [feat] #100 친구모아보기 부분 서버통신 완료
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/Cell/FriendListCVC.xib
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/Cell/MyPageHomeFriendCVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/Cell/MyPageHomeTopCVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/DataModel/MyPageFriendResponse.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/MyPageHomeVC.swift
Labels: feat, pull request, server, silver

#115 [feat] #77 마이페이지 상세보기 화면 전환 완료
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/Cell/FriendListCVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/Cell/FriendListCVC.xib
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/MyPageHomeVC.swift
Labels: feat, pull request, silver

#117 [feat] #95 랜덤이미지 받아오기 closed
  Keepin_iOS/Keepin_iOS/Sources/Home/Cell/HomeTopTVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Home/Cell/HomeTopTVC.xib
  Keepin_iOS/Keepin_iOS/Sources/Home/DataManager/HomeDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/Home/HomeVC.swift
Labels: feat, pull request, seawater🌊, server

#122 [feat] #121 #34 스플래시 리마인더 캘린더
  Keepin_iOS/Keepin_iOS.xcodeproj/project.pbxproj
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icKeepinLoginLogo.imageset/Contents.json
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icKeepinLoginLogo.imageset/icKeepinLoginLogo.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icKeepinLoginLogo.imageset/icKeepinLoginLogo@2x.png
  Keepin_iOS/Keepin_iOS/Assets.xcassets/icKeepinLoginLogo.imageset/icKeepinLoginLogo@3x.png
  Keepin_iOS/Keepin_iOS/Info.plist
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderHome/ReminderVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderHome/ReminderVC.xib
  Keepin_iOS/Keepin_iOS/Sources/Splash/SplashVC.xib
Labels: 3wns, pull request

#123 [feat] #72 마이페이지 메인뷰 스크롤 수정
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/Cell/MyPageDetailPresentCVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/MyPageDetailVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/Cell/MyPageHomeFriendCVC.xib
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/MyPageHomeVC.swift
Labels: fix, silver

#124 [fix] #120 마이페이지 친구상세 탭바 수정
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/MyPageHomeVC.swift
Labels: fix, silver

#126 [fix] #125 마이페이지 친구상세 하단부분 수정
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/MyPageDetailVC.xib
Labels: fix, pull request, silver

#130 [fix] #129 모아보기 상세 하단 높이 조절
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentDetail/PresentDetailVC.xib
Labels: 3wns, pull request

#133 [fix] #128 프로필 편집 탭바 수정
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/MyPageHomeVC.swift
Labels: fix, pull request, silver

#134 [fix] #75 키핀하기 이미지 추가 버튼 변경
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusHome/Cell/KeepinPlusImageTVC.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusHome/Cell/KeepinPlusImageTVC.xib
Labels: fix, pull request, seawater🌊

#136 [fix] #127 마이페이지 친구 등록 탭바 수정
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/MyPageHomeVC.swift
Labels: fix, pull request, silver

#138 [fix] #137 dismisskeyboard 추가
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusHome/KeepinPlusVC.swift
Labels: fix, pull request, seawater🌊

#140 [fix] #139 alert 내용 수정
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusHome/KeepinPlusVC.swift
Labels: fix, pull request, seawater🌊

#141 [fix] #132 마이페이지 친구상세 네비게이션 바 수정
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/MyPageDetailVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/MyPageDetailVC.xib
Labels: fix, pull request, silver

#144 [feat] 선물 모아보기 서버 이미지 처리 완료
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentMoaHome/Cell/PresentMoaCVC.xib
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentMoaHome/PresentMoaVC.swift
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/Search/AfterCate/AfterCatVC.swift
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/Search/SearchVC.swift
Labels: 3wns, pull request

#147 [fix] 받은 선물 버튼 테두리 조정
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusHome/Cell/KeppinPlusSelectTVC.swift
Labels: fix, pull request, seawater🌊

#148 [fix] #119 마이페이지 메인뷰 네비게이션 바 수정
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/Cell/NavigationBarCVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/Cell/NavigationBarCVC.xib
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/MyPageHomeVC.swift
Labels: fix, pull request, silver

#150 [feat] #149 체인지뷰컨으로 로그인 돌아가기 막기
  Keepin_iOS/Keepin_iOS/Configuration/Extension/UIViewController.swift
  Keepin_iOS/Keepin_iOS/Sources/EmailLogin/DataManager/EmailLoginDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/EmailLogin/EmailLoginVC.swift
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentMoaHome/Cell/PresentMoaCVC.xib
Labels: 3wns, pull request

#152 [fix] #142 마이페이지 메인뷰 모아보기 셀 UI수정
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/Cell/FriendListCVC.xib
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/Cell/MyPageHomeFriendCVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/Cell/MyPageHomeFriendCVC.xib
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/MyPageHomeVC.swift
Labels: fix, pull request, silver

#155 [fix] #153 친구 상세보기 메모 placeholder수정
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/Cell/MyPageDetailMemoCVC.xib
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/Cell/MyPageDetailPresentCVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/MyPageDetailVC.swift
Labels: fix, pull request, silver

#156 [feat] 모아보기 최신/오래된 서버 완료
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentDetail/PresentDetailVC.swift
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentDetail/PresentDetailVC.xib
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentMoaHome/Cell/PresentDetailCVC.swift
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentMoaHome/Cell/PresentDetailCVC.xib
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentMoaHome/DataManager/PresentMoaHomeDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentMoaHome/PresentMoaVC.swift
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentMoaHome/PresentMoaVC.xib
Labels: 3wns, pull request

#157 [feat] #109 모아보기 상세 서버 완료
  Keepin_iOS/Keepin_iOS/Configuration/Extension/UIButton.swift
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentDetail/PresentDetailVC.swift
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentDetail/PresentDetailVC.xib
Labels: 3wns, feat, server

#158 [fix] 키핀하기 뷰
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusHome/Cell/KeepinPlusWriteTVC.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusHome/Cell/KeepinPlusWriteTVC.xib
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusHome/KeepinPlusVC.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusHome/KeepinPlusVC.xib
Labels: fix, pull request, seawater🌊

#163 [fix] #162 홈 autolayout 잡음
  Keepin_iOS/Keepin_iOS/Sources/Home/Cell/HomeTopSingleTVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Home/Cell/HomeTopSingleTVC.xib
  Keepin_iOS/Keepin_iOS/Sources/Home/HomeVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Home/HomeVC.xib
Labels: assignment, fix, pull request, seawater🌊

#165 [fix] 선물 모아보기 오토레이아웃
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentDetail/PresentDetailVC.swift
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentMoaHome/PresentMoaVC.swift
Labels: 3wns, pull request

#168 [fix] 선물 모아보기 셀 재사용 초기화
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentMoaHome/Cell/PresentMoaCVC.swift
Labels: 3wns, pull request

#169 [feat] 홈 하단 리마인더 서버통신
  Keepin_iOS/Keepin_iOS/Sources/Home/Cell/HomeEventTVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Home/Cell/HomeEventTVC.xib
  Keepin_iOS/Keepin_iOS/Sources/Home/HomeVC.swift
Labels: feat, pull request, seawater🌊

#171 [fix] #170 첫화면 레이아웃 완료
  Keepin_iOS/Keepin_iOS/Sources/Login/LoginFirstVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Login/LoginFirstVC.xib
Labels: pull request, seawater🌊

#176 [feat] #175 리마인더 선택 월 흰색으로
  Keepin_iOS/Keepin_iOS/Configuration/Extension/Date.swift
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentMoaHome/Cell/PresentMoaCVC.xib
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderHome/Cell/ReminderCVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderHome/Cell/ReminderCVC.xib
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderHome/ReminderVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderHome/ReminderVC.xib
Labels: 3wns, pull request

#177 [feat] 마이페이지 상세 부분 서버통신(데이터 전달 전까지)
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/Cell/MyPageDetailTopCVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/DataManager/MyPageDetailDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/DataModel/MyPageDetailResponse.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/MyPageDetailVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/Cell/FriendListCVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/Cell/FriendListCVC.xib
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/Cell/MyPageHomeFriendCVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/Cell/MyPageHomeTopCVC.xib
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/DataManager/MyPageHomeDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/MyPageHomeVC.swift
Labels: feat, pull request, server, silver

#179 [fix] #178 리마인더 스크롤 버그 수정
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderHome/ReminderVC.swift
Labels: 3wns, pull request

#180 [fix] #174 마이페이지 메인뷰 오토레이아웃 수정
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/Cell/FriendListCVC.xib
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/Cell/MyPageHomeFriendCVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/Cell/MyPageHomeHeaderCVC.xib
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/Cell/MyPageHomeTopCVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/Cell/MyPageHomeTopCVC.xib
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/MyPageHomeVC.swift
Labels: assignment, fix, pull request, silver

#183 [fix] #182 마이페이지 메인뷰 상단부분 총개수 수정하기
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/MyPageHomeVC.swift
Labels: fix, pull request, silver

#185 [fix] 리마인더 리스트 레이아웃 수정
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderHome/Cell/ReminderTVC.xib
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderHome/ReminderVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderHome/ReminderVC.xib
Labels: 3wns, pull request

#186 [feat] #173 se2 하단 리마인더 중요표시까지 연결 완료
  Keepin_iOS/Keepin_iOS/Sources/Home/Cell/HomeTopSingleTVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Home/Cell/HomeTopSingleTVC.xib
  Keepin_iOS/Keepin_iOS/Sources/Home/HomeVC.swift
Labels: pull request, seawater🌊

#187 [feat] #116 친구 상세보기 상단부분 서버 통신
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusHome/Cell/KeppinPlusSelectTVC.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusHome/Cell/KeppinPlusSelectTVC.xib
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/MyPageDetailVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/MyPageHomeVC.swift
Labels: feat, pull request, server, silver

#188 [fix] 키핀하기 오토레이아웃 완료
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusHome/Cell/KeepinPlusImageTVC.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusHome/Cell/KeepinPlusImageTVC.xib
Labels: assignment, fix, pull request, seawater🌊

#189 [fix] #181 마이페이지 친구상세 오토레이아웃 완료
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/Cell/MyPageDetailMemoCVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/Cell/MyPageDetailMemoCVC.xib
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/Cell/MyPageDetailPresentCVC.xib
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/Cell/MyPageDetailTopCVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/Cell/MyPageDetailTopCVC.xib
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/Cell/MyPageHomeTopCVC.xib
Labels: assignment, fix, pull request, silver

#191 [fix] 모아보기 상세 오토레이아웃
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentDetail/PresentDetailVC.swift
Labels: 3wns, assignment, fix, pull request

#193 [feat] #192 친구 메모 서버 통신, 불필요한 print문 삭제
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/Cell/MyPageDetailPresentCVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/DataManager/MyPageDetailDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/MyPageDetailVC.swift
Labels: feat, fix, pull request, server, silver

#195 [fix] #194 선물컬렉션 오토레이아웃 수정
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentDetail/PresentDetailVC.swift
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentDetail/PresentDetailVC.xib
Labels: 3wns, assignment, fix, pull request

#197 [fix] #196 선물모아보기 오토레이아웃
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderHome/Cell/ReminderTVC.xib
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderHome/ReminderVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderHome/ReminderVC.xib
Labels: 3wns, assignment, fix, pull request

#200 [fix] #199 프로필 설정 오토레이아웃 수정
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/MyPageProfileVC.xib
Labels: assignment, fix, pull request, silver

#202 [fix] #201 프로필 편집 이름 수정 오토레이아웃 수정
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/EditProfile/MyPageEditNameVC.xib
Labels: assignment, fix, pull request, silver

#204 [fix] #203 비밀번호, 휴대폰 번호 수정 오토레이아웃 잡기
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/EditProfile/MyPageEditPhoneVC.xib
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/EditProfile/MyPageEditPwVC.xib
Labels: assignment, fix, silver

#206 [feat] #205 리마인더 월별조회 서버통신
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderHome/Cell/ReminderTVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderHome/DataManager/ReminderHomeDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderHome/DataModel/ReminderHomeRequest.swift
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderHome/DataModel/ReminderHomeResponse.swift
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderHome/ReminderVC.swift
Labels: 3wns, feat, pull request, server

#209 [feat] #208 리마인더 상세 서버통신
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderAdd/DataManager/ReminderDetailDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderAdd/DataModel/ReminderDetailDataResponse.swift
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderAdd/ReminderAddVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderHome/DataManager/ReminderHomeDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderHome/DataModel/ReminderHomeResponse.swift
Labels: 3wns, feat, pull request, server

#214 [feat] 친구검색 뷰 UI완성
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusHome/Cell/KeepinPlusSearchTVC.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusHome/Cell/KeepinPlusSearchTVC.xib
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusHome/KeepinPlusVC.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/SelectFriend/Cell/SelectFriendListTVC.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/SelectFriend/Cell/SelectFriendListTVC.xib
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/SelectFriend/Cell/SelectFriendTitleTVC.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/SelectFriend/Cell/SelectFriendTitleTVC.xib
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/SelectFriend/SelectFriendVC.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/SelectFriend/SelectFriendVC.xib
Labels: pull request, seawater🌊

#216 [refactor] 코드 리팩토링
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentDetail/DataManager/PresentDetailDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentDetail/PresentDetailVC.swift
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentMoaHome/PresentMoaVC.swift
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/Search/AfterCate/AfterCatVC.swift
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/Search/DataManager/SearchDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/Search/SearchVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderAdd/DataManager/ReminderDetailDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderAdd/DataModel/ReminderDetailRequest.swift
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderAdd/ReminderAddVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderHome/ReminderVC.swift
Labels: 3wns, assignment, refactor

#217 [feat] #118 친구상세 서버통신 받은 부분
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/Cell/MyPageDetailMemoCVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/Cell/MyPageDetailPresentMoaCVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/DataManager/MyPageDetailDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/DataManager/MyPagePresentMoaDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/DataModel/MyPagePresentMoaResponse.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/MyPageDetailVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/Cell/FriendListCVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/DataManager/MyPageHomeDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/MyPageHomeVC.swift
Labels: feat, pull request, server, silver

#219 [feat] 키핀하기 데이터전달
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusHome/KeepinPlusVC.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/SelectFriend/SelectFriendVC.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/SelectFriend/SelectFriendVC.xib
Labels: pull request, seawater🌊

#221 [refactor] #220 코드 리팩터링
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusFriend/KeepinPlusFriendVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/Cell/MyPageDetailMemoCVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/Cell/MyPageDetailPresentCVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/Cell/MyPageDetailPresentMoaCVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/Cell/MyPageDetailTopCVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/DataManager/MyPageDetailDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/DataManager/MyPagePresentMoaDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/MyPageDetailVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/MyPageFriendFixVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/Cell/FriendListCVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/Cell/MyPageHomeFriendCVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/Cell/MyPageHomeHeaderCVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/Cell/MyPageHomeTopCVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/MyPageHomeVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/EditProfile/MyPageEditNameVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/EditProfile/MyPageEditPhoneVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/EditProfile/MyPageEditPwVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/MyPageProfileVC.swift
Labels: pull request, refactor, silver, style

#222 [feat] #213 리마인더 등록 서버통신
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderAdd/DataManager/ReminderDetailDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderAdd/DataModel/ReminderDetailResponse.swift
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderAdd/ReminderAddVC.swift
Labels: 3wns, feat, pull request, server

#224 [feat] 키핀하기 서버, 친구선택 친구목록 가져오기
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusHome/DataManager/KeepinPlusHomeDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusHome/DataModel/KeepinPlusHomeRequest.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusHome/DataModel/KeepinPlusHomeResponse.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusHome/KeepinPlusVC.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusHome/KeepinPlusVC.xib
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/SelectFriend/SelectFriendVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/DataManager/MyPageHomeDataManager.swift
Labels: pull request, seawater🌊

#226 [feat] #212 리마인더 삭제 서버통신
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderAdd/DataManager/ReminderDetailDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderAdd/ReminderAddVC.swift
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderHome/DataManager/ReminderHomeDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderHome/DataModel/ReminderHomeRequest.swift
  Keepin_iOS/Keepin_iOS/Sources/Reminder/ReminderHome/ReminderVC.swift
Labels: 3wns, feat, pull request, server

#228 [feat] #227 선물모아보기 삭제 서버통신
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentDetail/DataManager/PresentDetailDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentDetail/DataModel/PresentDetailRequest.swift
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentDetail/PresentDetailVC.swift
  Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentMoaHome/PresentMoaVC.swift
Labels: 3wns, feat, pull request, server

#230 [feat] #229 친구 상세 상단부분 서버통신 완료
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/DataManager/MyPageDetailDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/DataManager/MyPagePresentMoaDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/DataModel/MyPageDetailResponse.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/DataModel/MyPagePresentMoaResponse.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/MyPageDetailVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/Cell/MyPageHomeFriendCVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/MyPageHomeVC.swift
Labels: feat, pull request, server, silver

#231 [feat] #118 친구 상세 선물 모아보기 받은,준 서버통신 완료
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/DataManager/MyPagePresentMoaDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/DataModel/MyPagePresentMoaCVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/DataModel/MyPagePresentMoaResponse.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/MyPageDetailVC.swift
Labels: feat, pull request, server, silver

#232 [fix] #73 친구 상세보기 스크롤 수정하기
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/MyPageDetailVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/MyPageDetailVC.xib
Labels: fix, pull request, silver

#233 [feat] 새친구 등록하기 파일 위치 변경
  Keepin_iOS/Keepin_iOS.xcodeproj/project.pbxproj
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/KeepinPlusFriendVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/KeepinPlusFriendVC.xib
Labels: feat, pull request, silver

#235 [feat] #234 새친구 등록하기 서버통신
  Keepin_iOS/Keepin_iOS.xcodeproj/project.pbxproj
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/DataManager/PlusFriendDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/DataModel/PlusFriendRequest.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/DataModel/PlusFriendResponse.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/KeepinPlusFriendVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/KeepinPlusFriendVC.xib
Labels: feat, pull request, server, silver

#239 [feat] #236 친구삭제하기 파일추가, 서버통신
  Keepin_iOS/Keepin_iOS.xcodeproj/project.pbxproj
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/DataManager/MyPageDetailDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/DataModel/MyPageDetailRequest.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/DataModel/MyPageDetailResponse.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/DataModel/MyPageFriendDeleteResponse.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/MyPageDetailVC.swift
Labels: feat, pull request, server, silver

#241 [fix] #238 친구상세 네비게이션 바 수정
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/MyPageFriendFixVC.swift
Labels: fix, silver

#242 [feat] #237 친구상세 이름 수정 서버통신
  Keepin_iOS/Keepin_iOS.xcodeproj/project.pbxproj
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/DataManager/MyPageDetailDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/DataModel/MyPageFixRequest.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/MyPageDetailVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/MyPageFriendFixVC.xib
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/Cell/MyPageHomeFriendCVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/MyPageHomeVC.swift
Labels: feat, pull request, server, silver

#244 [feat] #243 프로필 편집 이름수정 서버통신
  Keepin_iOS/Keepin_iOS.xcodeproj/project.pbxproj
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/DataManager/MyPageProfileDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/DataModel/MyPageProfileNameRequest.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/DataModel/MyPageProfileNameResponse.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/EditProfile/MyPageEditNameVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/EditProfile/MyPageEditNameVC.xib
Labels: feat, pull request, server, silver

#247 [feat] #245 프로필 편집 전화번호 수정 서버통신
  Keepin_iOS/Keepin_iOS.xcodeproj/project.pbxproj
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/DataManager/MyPageProfileDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/DataModel/MyPageProfilePhoneRequest.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/DataModel/MyPageProfilePhoneResponse.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/EditProfile/MyPageEditPhoneVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/EditProfile/MyPageEditPhoneVC.xib
Labels: feat, pull request, server, silver

#248 [feat] #246 프로필 편집 비밀번호 수정 서버통신
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/DataManager/MyPageProfileDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/DataModel/MyPageProfilePhoneResponse.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/EditProfile/MyPageEditPwVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/EditProfile/MyPageEditPwVC.xib
Labels: feat, server, silver

#252 [feat] #251 프로필 조회 서버통신
  Keepin_iOS/Keepin_iOS.xcodeproj/project.pbxproj
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/DataManager/MyPageProfileDataManager.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/DataModel/MyPageProfileInfoResponse.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/MyPageProfileVC.swift
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/MyPageProfileVC.xib
Labels: feat, server, silver

#253 [feat] 새친구 등록하기 파일 위치 변경
  Keepin_iOS/Keepin_iOS.xcodeproj/project.pbxproj
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusFriend/KeepinPlusFriendVC.swift
  Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusFriend/KeepinPlusFriendVC.xib
Labels: feat, silver

#255 [fix] #254 친구삭제 다이얼로그 수정하기
  Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageDetail/MyPageDetailVC.swift
Labels: fix, silver
